# Generated by Django 3.0 on 2019-12-17 20:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_merge_20180905_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('CID', models.IntegerField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=25)),
                ('Last_Name', models.CharField(max_length=25)),
                ('Email', models.EmailField(blank=True, max_length=50, null=True)),
                ('HomeNumber', models.CharField(max_length=25)),
                ('MobileNumber', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='internship_history',
            name='Stop_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='past_employees',
            name='Date_of_Birth',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='past_employees',
            name='Middle_Name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='past_employees',
            name='Title',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('BID', models.IntegerField(primary_key=True, serialize=False)),
                ('Recipient_Name', models.CharField(max_length=25)),
                ('Number_Of_Showing', models.IntegerField(max_length=10)),
                ('Text_Content', models.TextField(blank=True)),
                ('Air_Date', models.DateField(blank=True, null=True)),
                ('Date_Created', models.DateField(blank=True, null=True)),
                ('CID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.customer')),
            ],
        ),
    ]
