# Generated by Django 3.0 on 2019-12-17 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20191217_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_degrees',
            name='PastEmployeeID',
        ),
        migrations.RemoveField(
            model_name='employment_history',
            name='PastEmployeeID',
        ),
        migrations.RemoveField(
            model_name='internship_history',
            name='InternID',
        ),
        migrations.RemoveField(
            model_name='qualifications_on_entry',
            name='InternID',
        ),
        migrations.DeleteModel(
            name='countries',
        ),
        migrations.DeleteModel(
            name='employee_degrees',
        ),
        migrations.DeleteModel(
            name='employment_history',
        ),
        migrations.DeleteModel(
            name='internship_history',
        ),
        migrations.DeleteModel(
            name='past_employees',
        ),
        migrations.DeleteModel(
            name='personal_information',
        ),
        migrations.DeleteModel(
            name='qualifications_on_entry',
        ),
    ]
