# Generated by Django 3.0 on 2019-12-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20191217_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Number_Of_Showing',
            field=models.IntegerField(),
        ),
    ]
